# baseport
PREFERRED_VERSION_x-load =		"4.59"
PREFERRED_VERSION_u-boot =		"5.06"
PREFERRED_VERSION_linux-tiomap =	"2.6.24.7-5.19"

# bridge and friends
PREFERRED_VERSION_tidspbridge-module =	"23.11"
PREFERRED_VERSION_tidspbridge-lib =	"23.11"

# openmax
PREFERRED_VERSION_tiopenmax =		"3.17"

# gstreamer
PREFERRED_VERSION_libgoo =		"5.11"
PREFERRED_VERSION_gst-goo =		"5.11"
PREFERRED_VERSION_gst-pyapps =		"5.11"

# connectivity
PREFERRED_VERSION_wilink = 		"23-1.1"
PREFERRED_VERSION_btfm = 		"23-1.1"
