# baseport
PREFERRED_VERSION_u-boot =             "5.06"
PREFERRED_VERSION_linux-tiomap =       "2.6.24.7-5.19"

# bridge and friends
PREFERRED_VERSION_tidspbridge-module = "23.11"
PREFERRED_VERSION_tidspbridge-lib =    "23.11"
#PREFERRED_VERSION_tidspbridge-extra =  "23.10"
#PREFERRED_VERSION_tisocketnodes =      "23.10"

# openmax
PREFERRED_VERSION_tiopenmax =          "3.17"

# gstreamer
PREFERRED_VERSION_libgoo =             "5.11"
PREFERRED_VERSION_gst-goo =            "5.11"
