# baseport
PREFERRED_VERSION_x-load =		"4.60"
PREFERRED_VERSION_u-boot =		"5.07"
PREFERRED_VERSION_linux-tiomap =	"2.6.24.7-5.20"

# bridge and friends
PREFERRED_VERSION_tidspbridge-module =	"23.12"
PREFERRED_VERSION_tidspbridge-lib =	"23.12"
PREFERRED_VERSION_tidspbridge-samples =	"4.52-P1"

# openmax
#PREFERRED_PROVIDER_virtual/openmax-il =		"meta-tiopenmax"
PREFERRED_PROVIDER_virtual/openmax-il =		"meta-tiopenmax-complete"
PREFERRED_VERSION_tiopenmax =			"3.17"
PREFERRED_VERSION_tiopenmax-core =		"3.17"
PREFERRED_VERSION_tiopenmax-clock =		"3.17"
PREFERRED_VERSION_tiopenmax-perf =		"3.17"
PREFERRED_VERSION_tiopenmax-lcml =		"3.17"
PREFERRED_VERSION_tiopenmax-policymanager =	"3.17"
PREFERRED_VERSION_tiopenmax-audiomanager =	"3.17"
PREFERRED_VERSION_tiopenmax-resourcemanager =	"3.17"
PREFERRED_VERSION_tiopenmax-jpegdec =		"3.17"
PREFERRED_VERSION_tiopenmax-jpegenc =		"3.17"

# gstreamer
PREFERRED_VERSION_libgoo =		"5.11"
PREFERRED_VERSION_gst-goo =		"5.11"
PREFERRED_VERSION_gst-pyapps =		"5.11"

# connectivity
PREFERRED_VERSION_wilink = 		"23-1.1"
PREFERRED_VERSION_btfm = 		"23-1.1"
PREFERRED_VERSION_openobex =            "1.3"

# gfx
PREFERRED_VERSION_sgx-kernel-module =	"1.3"
PREFFERED_VERSION_sgx-lib-noxws =	"1.3"
