# baseport
PREFERRED_VERSION_u-boot =             "23.10"
PREFERRED_VERSION_linux-tiomap =       "2.6.24.7"

# bridge and friends
PREFERRED_VERSION_tidspbridge-module = "23.10"
PREFERRED_VERSION_tidspbridge-lib =    "23.10"
PREFERRED_VERSION_tidspbridge-extra =  "23.10"
PREFERRED_VERSION_tisocketnodes =      "23.10"

# openmax
PREFERRED_VERSION_tiopenmax =          "23.10"

# gstreamer
PREFERRED_VERSION_libgoo =             "5.10"
PREFERRED_VERSION_gst-goo =            "5.10"
